doc: add doc for versioned deployment
csi-addons/kubernetes-csi-addons pull request #123
Opened 2022-02-28 10:30 UTC by yati1998

This commit updates README with another way to deploy
the controller which is "using the yamls file"

Signed-off-by: yati1998 <ypadia@redhat.com>

2022-02-28 12:09 UTC, nixpanic requested changes
It would be good to mention that versioned deployment is possible with the yaml files that get generated for a release, like https://github.com/csi-addons/kubernetes-csi-addons/releases/tag/v0.3.0. Download the yaml files from there, or use them directly with `kubectl`.

2022-02-28 12:09 UTC, nixpanic commented on README.md
> +cd deploy/controller
missing the `$` as command prefix

2022-02-28 12:32 UTC, nixpanic approved these changes

2022-03-01 06:25 UTC, Madhu-1 approved these changes

2022-03-01 06:26 UTC, merged