Add reclaim space protobuf file
csi-addons/kubernetes-csi-addons pull request #16
Opened 2021-12-16 12:22 UTC by yati1998

This commit adds the protobuf file which includes the spec
for communication between the CSIAddons Controller and sidecar.

Signed-off-by: yati1998 <ypadia@redhat.com>

2021-12-16 12:27 UTC, Rakshith-R requested changes
Let this package go inside reclaimspace package like
`internal/service/reclaimspace` to better accommodate other services.

2021-12-16 12:37 UTC, Rakshith-R commented
Please add a new makefile to generate go files from protoc files or modify existing makefile or both.
Thanks

2021-12-16 12:42 UTC, yati1998 commented
> Please add a new makefile to generate go files from protoc files or modify existing makefile or both. Thanks

After talking to @nixpanic , he suggested to directly write the protobuf file. @nixpanic What's your thought here? shall I write the README to create the protobuf?

2021-12-16 13:01 UTC, Rakshith-R requested changes
Just makefile with commands to generate go files.

2021-12-16 13:01 UTC, Rakshith-R commented on internal/service/reclaimspace/reclaimspace.proto
> +option go_package = "github.com/csi-addons/kubernetes-csi-addons/internal/service";
This needs to be updated.

2021-12-16 13:03 UTC, nixpanic commented
> > Please add a new makefile to generate go files from protoc files or modify existing makefile or both. Thanks
> 
> After talking to @nixpanic , he suggested to directly write the protobuf file. @nixpanic What's your thought here? shall I write the README to create the protobuf?

There is no need to place the `protobuf` parts in a readme. This is internal to this repository only, not shared for some external API.

There might be a benefit in automatically re-generating the go files from the `.proto` file, but I do not think we need to do that now. If we really think it helps, we can always add such automation later.

2021-12-16 13:05 UTC, nixpanic commented
> Just makefile with commands to generate go files.

The problem is installing the `protoc` components... The way it is done in csi-addons/spec is not clean, so I prefer manual generation before we add automation around this and other parts of the project.

2021-12-16 13:05 UTC, nixpanic commented on internal/service/reclaimspace/reclaimspace.proto
> +option go_package = "github.com/csi-addons/kubernetes-csi-addons/internal/service";
updated to what?

2021-12-16 13:08 UTC, nixpanic requested changes

2021-12-16 13:08 UTC, nixpanic commented on internal/service/reclaimspace/reclaimspace.proto
> +  }
formatting is a little weird, please check indention and add empty lines after a closing `}`

2021-12-16 13:08 UTC, nixpanic commented on internal/service/reclaimspace/reclaimspace.proto
> +// SidecarCSIAddonsResponse holda the information about the result of the
Please review the comments, `SidecarCSIAddonsResponse` is not correct (and `holda` typo)

2021-12-16 13:08 UTC, nixpanic commented on internal/service/reclaimspace/reclaimspace.proto
> +  }
indention?

2021-12-17 05:41 UTC, Rakshith-R requested changes

2021-12-17 05:41 UTC, Rakshith-R commented on internal/service/reclaimspace/reclaimspace.proto
> +package service;
change this too and regenerate the proto files.
```suggestion
package reclaimspace;
```

2021-12-17 06:31 UTC, Rakshith-R reviewed
Looks good to me, I'll wait for @nixpanic review

2021-12-17 09:14 UTC, nixpanic approved these changes

2021-12-17 09:28 UTC, Rakshith-R approved these changes

2021-12-17 09:28 UTC, merged