deploy: adds and genrate vol-rep crds
csi-addons/kubernetes-csi-addons pull request #189
Opened 2022-07-26 05:40 UTC by yati1998

This commits converts the kuberentes-csi-addons to
multi-group and generates the required VR and VRC
crds.

Signed-off-by: yatipadia <ypadia@redhat.com>

2022-07-26 06:23 UTC, Rakshith-R requested changes
follow the steps to transition current apis and controller to multigroup folder layout
https://kubebuilder.io/migration/multi-group.html

2022-07-26 09:47 UTC, nixpanic commented
It seems a few files were modified/created, and those need to be checked in as well.

2022-07-28 10:38 UTC, yati1998 commented
> follow the steps to transition current apis and controller to multigroup folder layout https://kubebuilder.io/migration/multi-group.html

Hey, @Rakshith-R do you mean for adding controllers/ part , didn't get what is missed.

2022-07-29 09:54 UTC, Rakshith-R requested changes

2022-07-29 09:54 UTC, Rakshith-R commented on apis/replication.storage/v1alpha1/volumereplication_types.go
> +Licensed under the Apache License, Version 2.0 (the "License");
This needs to be changed

2022-07-29 09:54 UTC, Rakshith-R commented on apis/replication.storage/v1alpha1/volumereplicationclass_types.go
> +Licensed under the Apache License, Version 2.0 (the "License");
same here

2022-08-01 04:37 UTC, yati1998 commented
@Rakshith-R @nixpanic @Madhu-1

2022-08-01 04:45 UTC, Rakshith-R requested changes
Please add docs similar to reclaimspace and network fence
https://github.com/csi-addons/kubernetes-csi-addons/tree/main/docs

2022-08-01 05:10 UTC, Madhu-1 submitted a review, later dismissed
changes LGTM.

2022-08-01 09:28 UTC, Rakshith-R approved these changes

2022-08-01 09:32 UTC, Madhu-1 approved these changes

2022-08-01 09:33 UTC, merged