add proto and service for volume replication
csi-addons/kubernetes-csi-addons pull request #205
Opened 2022-08-18 12:07 UTC by Rakshith-R

- [proto: add proto for volume replication](https://github.com/csi-addons/kubernetes-csi-addons/commit/dbc993936b07b4a06fe9b9d4bb486679b8204404) 

> added required proto file and generate grpc library for internal communication
> for volume replication

Signed-off-by: Rakshith R <rar@redhat.com>

- [sidecar: add volume replication service setup](https://github.com/csi-addons/kubernetes-csi-addons/commit/e1489b33de76814532a410cf8b686b3063d6b579) 

> adding sidecar service for the volume replication service.

Signed-off-by: Rakshith R <rar@redhat.com>

Updates: #116

2022-08-19 04:10 UTC, yati1998 requested changes
Please check the CI errors and correct them. Also, I assume these changes are transferred from the volume replication operator, if yes, it will be good to add the link to it in the commit-msg or PR description.

2022-08-19 04:14 UTC, Madhu-1 commented on internal/sidecar/service/volumereplication.go
> +		return nil, status.Error(codes.InvalidArgument, err.Error())
Always try the internal server error if the invalid is not the right error.

2022-08-19 04:14 UTC, Madhu-1 commented on internal/sidecar/service/volumereplication.go
> +		&csiReplication.PromoteVolumeRequest{
PromoteVolReq also has the force option which you need to consider

2022-08-19 04:14 UTC, Madhu-1 commented on internal/sidecar/service/volumereplication.go
> +	_, err = rs.controllerClient.ResyncVolume(ctx,
Resync should return success or failure based on that we need to take few actions to reconcile the CR or not.

2022-08-22 07:02 UTC, Rakshith-R commented
> Please check the CI errors and correct them.

done

>Also, I assume these changes are transferred from the volume replication operator, if yes, it will be good to add the link to it in the commit-msg or PR description.

Negative, this purely csi-addons design of internal proto and sidecar, I'll add them for controller part.
---

Other requested changes are addressed, PTAL.

2022-08-22 07:04 UTC, Madhu-1 approved these changes

2022-08-22 09:40 UTC, yati1998 approved these changes

2022-08-22 09:40 UTC, merged