relcaimspace: add nodeID to error message
csi-addons/kubernetes-csi-addons pull request #256
Opened 2022-10-18 10:02 UTC by Madhu-1

add nodeID to error message to provide more details for debugging.

Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

2022-10-18 10:07 UTC, Rakshith-R requested changes

2022-10-18 10:07 UTC, Rakshith-R commented on controllers/csiaddons/reclaimspacejob_controller.go
> +		err = fmt.Errorf("Controller and Node Client not found for %s nodeID", target.nodeID)
```suggestion
		err = fmt.Errorf("Controller and Node Client not found for %q nodeID", target.nodeID)
```
add quotes so it stands out ?

2022-10-18 10:07 UTC, Rakshith-R commented on controllers/csiaddons/reclaimspacejob_controller.go
> +		return nil, fmt.Errorf("node Client not found for %s nodeID", target.nodeID)
```suggestion
		return nil, fmt.Errorf("node Client not found for %q nodeID", target.nodeID)
```
add quotes so it stands out ?

2022-10-18 10:31 UTC, Rakshith-R approved these changes

2022-10-19 02:44 UTC, yati1998 approved these changes

2022-10-19 02:44 UTC, merged