controller/replication: add UnimplementedError for getVolRepInfo()
csi-addons/kubernetes-csi-addons pull request #295
Opened 2023-02-06 09:23 UTC by Rakshith-R

This commit adds code to handle UnimplmentedError from getVolumeReplicationInfo rpc. The controller wil now ignore this error and not requeue the request.

Fixes: #236

Signed-off-by: Rakshith R <rar@redhat.com>

2023-02-06 13:01 UTC, Madhu-1 submitted a review, later dismissed

2023-02-06 13:36 UTC, yati1998 requested changes

2023-02-06 13:36 UTC, yati1998 commented on internal/util/error.go
> +// IsUmplementedError returns true if the error is Unimplemented error.
IsUmplementedError-> IsUnimplementedError

2023-02-07 07:12 UTC, yati1998 approved these changes

2023-02-07 07:14 UTC, Madhu-1 approved these changes

2023-02-07 07:15 UTC, merged