build: use Go 1.20 as Kubernetes packages require that too
csi-addons/kubernetes-csi-addons pull request #363
Opened 2023-06-06 12:20 UTC by nixpanic

In preparation for updating the Kubernetes dependencies to v1.27 or newer, start using Go 1.20 now already.

2023-06-06 14:27 UTC, Rakshith-R requested changes

2023-06-06 14:27 UTC, Rakshith-R commented on .github/workflows/build-push.yaml
>        - name: Install Go 1.19
```suggestion
      - name: Set up Golang
```

nit:
Let's change this to a generic name.
Other workflows also need the same change.

2023-06-07 08:31 UTC, Rakshith-R approved these changes

2023-06-12 09:28 UTC, Madhu-1 approved these changes

2023-06-12 09:35 UTC, merged