ci: build container image on one arch
csi-addons/kubernetes-csi-addons pull request #39
Opened 2021-12-22 15:33 UTC by Madhu-1

To fasten the CI jobs for testing builds, build container images only on one arch and when pushing build on all arch.

Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

2021-12-22 15:38 UTC, Madhu-1 commented
build time from 25+ minutes is reduced to 1 min

2021-12-22 15:52 UTC, nixpanic requested changes
> build time from 25+ minutes is reduced to 1 min

Sure, but that might break the build. It would prevent pushing the image after merging, and there is no obvious failure reported in case that happens.

I don't think these delays are critical.

Maybe drop s390x and maype ppc64le only? These are not architectures that are commonly available for users that consume community provided components (as opposed to enterprise products).

2021-12-22 15:56 UTC, Madhu-1 commented
25+, not it's taking more than 45+ minutes and still goining. I don't think testing all PR's on all arch is required and not all images will be CI tested only build will be tested. if any failure on the pushing it can be addressed immediately  just because of that we should not slow down the entire CI

2021-12-22 15:58 UTC, nixpanic commented
> if any failure on the pushing

How are we getting informed about this? It should create a blocking issue, no other PRs may get merged until the build work again. If that can be guaranteed somehow, building for CI jobs on a single architecture is ok.

2021-12-22 16:03 UTC, Madhu-1 commented
> > if any failure on the pushing
> 
> How are we getting informed about this? It should create a blocking issue, no other PRs may get merged until the build work again. If that can be guaranteed somehow, building for CI jobs on a single architecture is ok.

we can configure slack to get notifications and add some action to send mails etc.

2021-12-22 16:11 UTC, nixpanic commented
> we can configure slack to get notifications and add some action to send mails etc.

Yes, and until that is done, we should keep building on all architectures we want (s390x and ppc64le can be dropped IMHO).

2021-12-22 16:12 UTC, Madhu-1 commented
okay for now s390x and ppc64le dropped

2021-12-22 16:40 UTC, nixpanic requested changes
> okay for now s390x and ppc64le dropped

Drop if from the build-push workflow too. Otherwise it is still possible to break the build without noticing.

2021-12-23 01:45 UTC, Rakshith-R approved these changes

2021-12-23 02:13 UTC, merged