Replicaiton: set volumeID in ReplicationSource for the volumeReplication
csi-addons/kubernetes-csi-addons pull request #596
Opened 2024-06-19 10:29 UTC by Madhu-1

update csi-addons spec to the latest commit and set voluemID in the ReplicationSource for the volume replication.

2024-06-19 12:23 UTC, nixpanic requested changes

2024-06-19 12:23 UTC, nixpanic commented on internal/sidecar/service/volumereplication.go
> +		ReplicationId: req.ReplicationId,
attributes of gRPC requests should not be accessed directly, use `req.GetReplicationId()` instead. And everywhere else, specially in new code.

2024-06-20 08:28 UTC, nixpanic approved these changes

2024-06-20 08:42 UTC, Rakshith-R approved these changes

2024-06-20 08:43 UTC, merged